services:
  drbot:
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    container_name: drbot
    restart: unless-stopped
    read_only: true
    volumes:
      - ${MEDIA_PATH}:/Media:ro
    environment:
      - DISCORD_OWNER=${DISCORD_OWNER}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MEDIA_PATH=/Media
      - REDIS_URL=redis://redis:6379
      - SCAN_MEDIA_ON_START=${SCAN_MEDIA_ON_START}
      - WATCH_MEDIA=${WATCH_MEDIA}
  
  redis:
    extends:
      file: redis.yaml
      service: redis
