name: Bun CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install
        working-directory: ./bot
        run: bun i --frozen-lockfile
      - name: Lint
        working-directory: ./bot
        run: bun run lint
#      - name: Test
#        working-directory: ./bot
#        run: npm test
      - name: Build (dev)
        working-directory: ./bot
        run: bun run build
        env:
          CI: true
      - name: Build (release)
        working-directory: ./bot
        run: bun run build:release
        env:
          CI: true
