name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        working-directory: ./bot
        run: npm ci --no-audit
      - name: Lint
        working-directory: ./bot
        run: npm run lint --if-present
#      - name: Test
#        working-directory: ./bot
#        run: npm test
      - name: Build
        working-directory: ./bot
        run: npm run build --if-present
        env:
          CI: true
